AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/DoubleNegation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 14

Lint/EmptyBlock:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: e

Metrics/ParameterLists:
  Max: 7

Layout/LineLength:
  Max: 160
