# RuboCop cops are not loaded by default in this repo
# Downstream consumers can enable them by adding:
# require:
#   - axn/rubocop

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 70

Metrics/PerceivedComplexity:
  Max: 20

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 20

Lint/EmptyBlock:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: e, on, id, if

Metrics/ParameterLists:
  Max: 10

Layout/LineLength:
  Max: 160


