# frozen_string_literal: true

source "https://rubygems.org"

# Use the local axn gem for testing
gem "axn", path: "../../"

# Rails dependencies
gem "rails", "~> 7.0"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 2.0"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 7.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder", "~> 2.7"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false

group :development, :test do
  gem "pry-byebug", "3.11.0"
  gem "sidekiq", "~> 7" # Background job processor -- when update, ensure `process_context_to_sidekiq_args` is still compatible
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
  gem "rubocop", "~> 1.21"
end

group :test do
  # These are only needed for development of Axn itself
  gem "faraday", "~> 2.0" # For client strategy testing
  gem "rspec", "~> 3.2"
end
